### ISSUE TITLE
EconomyAPI not found

### ISSUE THREAD

**Issue by GamerDaniel3000** [LolNova/HeadHunter#6]
**Describe the bug**
The plugin does not load but there is only one error in the console the EconomyAPI was not found.

**To Reproduce**
1. Download HeadHunter on GitHub.
2. Put the plugin in the plugins folder
3. Restart the Server
4. The plugin dont laod

**Expected behavior**

**Screenshots**
https://imgur.com/a/AJDKzvp

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LolNova** [comment]
Do you have EconomyAPI enabled on your server?

**Comment by GamerDaniel3000** [comment]
Do you have a updatet EconimyAPI plugin?

**Comment by LolNova** [comment]
Check poggit for an updated version of EconomyAPI, as stated the plugin won't work if EconomyAPI isn't activated on the server.
